# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa947e5472484b6a826c9005f03dd1bee0089822b8ab56ed1ff953fd07317e01637d5262074be805576159d24b9922c5c20fe9ccbda068719d55d5633026fce7

test:
  secret_key_base: 2f51982c72866594a2a1f7d6feba1f8bfec6e94a3efa537354ba2236fff544142a46a516986bb54e36669bfd2d9203e094242db33967683f2b9c0ad1509dfba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
